package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AndWhereExpression extends LogicalWhereExpression {
  public static final String concept = "DeCypher.structure.AndWhereExpression";

  public AndWhereExpression(SNode node) {
    super(node);
  }

  public static AndWhereExpression newInstance(SModel sm, boolean init) {
    return (AndWhereExpression) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.AndWhereExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AndWhereExpression newInstance(SModel sm) {
    return AndWhereExpression.newInstance(sm, false);
  }
}
