package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AvgReturnRetm extends FunctionalReturnTerm {
  public static final String concept = "DeCypher.structure.AvgReturnRetm";

  public AvgReturnRetm(SNode node) {
    super(node);
  }

  public static AvgReturnRetm newInstance(SModel sm, boolean init) {
    return (AvgReturnRetm) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.AvgReturnRetm", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AvgReturnRetm newInstance(SModel sm) {
    return AvgReturnRetm.newInstance(sm, false);
  }
}
