package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CollectReturnType extends FunctionalReturnTerm {
  public static final String concept = "DeCypher.structure.CollectReturnType";

  public CollectReturnType(SNode node) {
    super(node);
  }

  public static CollectReturnType newInstance(SModel sm, boolean init) {
    return (CollectReturnType) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.CollectReturnType", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CollectReturnType newInstance(SModel sm) {
    return CollectReturnType.newInstance(sm, false);
  }
}
