package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CountReturnTerm extends FunctionalReturnTerm {
  public static final String concept = "DeCypher.structure.CountReturnTerm";

  public CountReturnTerm(SNode node) {
    super(node);
  }

  public static CountReturnTerm newInstance(SModel sm, boolean init) {
    return (CountReturnTerm) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.CountReturnTerm", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CountReturnTerm newInstance(SModel sm) {
    return CountReturnTerm.newInstance(sm, false);
  }
}
