package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class DeCypher_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("2bff36db-590f-45b0-8915-8404dea505ff(DeCypher)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
