package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class FalseWhereExpression extends WhereExpression {
  public static final String concept = "DeCypher.structure.FalseWhereExpression";

  public FalseWhereExpression(SNode node) {
    super(node);
  }

  public static FalseWhereExpression newInstance(SModel sm, boolean init) {
    return (FalseWhereExpression) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.FalseWhereExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static FalseWhereExpression newInstance(SModel sm) {
    return FalseWhereExpression.newInstance(sm, false);
  }
}
