package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class FunctionalReturnTerm extends ReturnTerm implements INamedConcept {
  public static final String concept = "DeCypher.structure.FunctionalReturnTerm";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String RETURN_TERM = "returnTerm";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public FunctionalReturnTerm(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(FunctionalReturnTerm.NAME);
  }

  public void setName(String value) {
    this.setProperty(FunctionalReturnTerm.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(FunctionalReturnTerm.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(FunctionalReturnTerm.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(FunctionalReturnTerm.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(FunctionalReturnTerm.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(FunctionalReturnTerm.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(FunctionalReturnTerm.VIRTUAL_PACKAGE, value);
  }

  public ReturnTerm getReturnTerm() {
    return (ReturnTerm) this.getChild(ReturnTerm.class, FunctionalReturnTerm.RETURN_TERM);
  }

  public void setReturnTerm(ReturnTerm node) {
    super.setChild(FunctionalReturnTerm.RETURN_TERM, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(FunctionalReturnTerm.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, FunctionalReturnTerm.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, FunctionalReturnTerm.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(FunctionalReturnTerm.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, FunctionalReturnTerm.SMODEL_ATTRIBUTE, node);
  }

  public static FunctionalReturnTerm newInstance(SModel sm, boolean init) {
    return (FunctionalReturnTerm) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.FunctionalReturnTerm", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static FunctionalReturnTerm newInstance(SModel sm) {
    return FunctionalReturnTerm.newInstance(sm, false);
  }
}
