package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.baseLanguage.structure.IValidIdentifier;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class GraphNode extends BaseConcept implements IValidIdentifier {
  public static final String concept = "DeCypher.structure.GraphNode";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public GraphNode(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(GraphNode.NAME);
  }

  public void setName(String value) {
    this.setProperty(GraphNode.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(GraphNode.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(GraphNode.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(GraphNode.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(GraphNode.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(GraphNode.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(GraphNode.VIRTUAL_PACKAGE, value);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(GraphNode.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, GraphNode.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, GraphNode.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(GraphNode.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, GraphNode.SMODEL_ATTRIBUTE, node);
  }

  public static GraphNode newInstance(SModel sm, boolean init) {
    return (GraphNode) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.GraphNode", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static GraphNode newInstance(SModel sm) {
    return GraphNode.newInstance(sm, false);
  }
}
