package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class IDReturnTerm extends FunctionalReturnTerm {
  public static final String concept = "DeCypher.structure.IDReturnTerm";

  public IDReturnTerm(SNode node) {
    super(node);
  }

  public static IDReturnTerm newInstance(SModel sm, boolean init) {
    return (IDReturnTerm) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.IDReturnTerm", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static IDReturnTerm newInstance(SModel sm) {
    return IDReturnTerm.newInstance(sm, false);
  }
}
