package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class IndexQuery extends IndexQoL {
  public static final String concept = "DeCypher.structure.IndexQuery";
  public static final String VALUE = "value";

  public IndexQuery(SNode node) {
    super(node);
  }

  public String getValue() {
    return this.getProperty(IndexQuery.VALUE);
  }

  public void setValue(String value) {
    this.setProperty(IndexQuery.VALUE, value);
  }

  public static IndexQuery newInstance(SModel sm, boolean init) {
    return (IndexQuery) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.IndexQuery", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static IndexQuery newInstance(SModel sm) {
    return IndexQuery.newInstance(sm, false);
  }
}
