package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class IndexInitialization extends Initialization implements INamedConcept {
  public static final String concept = "DeCypher.structure.IndexInitialization";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String INDEX_QUERY = "indexQuery";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public IndexInitialization(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(IndexInitialization.NAME);
  }

  public void setName(String value) {
    this.setProperty(IndexInitialization.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(IndexInitialization.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(IndexInitialization.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(IndexInitialization.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(IndexInitialization.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(IndexInitialization.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(IndexInitialization.VIRTUAL_PACKAGE, value);
  }

  public IndexQoL getIndexQuery() {
    return (IndexQoL) this.getChild(IndexQoL.class, IndexInitialization.INDEX_QUERY);
  }

  public void setIndexQuery(IndexQoL node) {
    super.setChild(IndexInitialization.INDEX_QUERY, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(IndexInitialization.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, IndexInitialization.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, IndexInitialization.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(IndexInitialization.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, IndexInitialization.SMODEL_ATTRIBUTE, node);
  }

  public static IndexInitialization newInstance(SModel sm, boolean init) {
    return (IndexInitialization) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.IndexInitialization", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static IndexInitialization newInstance(SModel sm) {
    return IndexInitialization.newInstance(sm, false);
  }
}
