package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class IndexLookup extends IndexQoL implements INamedConcept {
  public static final String concept = "DeCypher.structure.IndexLookup";
  public static final String VALUE = "value";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public IndexLookup(SNode node) {
    super(node);
  }

  public String getValue() {
    return this.getProperty(IndexLookup.VALUE);
  }

  public void setValue(String value) {
    this.setProperty(IndexLookup.VALUE, value);
  }

  public String getName() {
    return this.getProperty(IndexLookup.NAME);
  }

  public void setName(String value) {
    this.setProperty(IndexLookup.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(IndexLookup.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(IndexLookup.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(IndexLookup.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(IndexLookup.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(IndexLookup.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(IndexLookup.VIRTUAL_PACKAGE, value);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(IndexLookup.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, IndexLookup.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, IndexLookup.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(IndexLookup.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, IndexLookup.SMODEL_ATTRIBUTE, node);
  }

  public static IndexLookup newInstance(SModel sm, boolean init) {
    return (IndexLookup) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.IndexLookup", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static IndexLookup newInstance(SModel sm) {
    return IndexLookup.newInstance(sm, false);
  }
}
