package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class IndexQoL extends BaseConcept {
  public static final String concept = "DeCypher.structure.IndexQoL";

  public IndexQoL(SNode node) {
    super(node);
  }

  public static IndexQoL newInstance(SModel sm, boolean init) {
    return (IndexQoL) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.IndexQoL", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static IndexQoL newInstance(SModel sm) {
    return IndexQoL.newInstance(sm, false);
  }
}
