package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Initialization extends BaseConcept {
  public static final String concept = "DeCypher.structure.Initialization";

  public Initialization(SNode node) {
    super(node);
  }

  public static Initialization newInstance(SModel sm, boolean init) {
    return (Initialization) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.Initialization", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Initialization newInstance(SModel sm) {
    return Initialization.newInstance(sm, false);
  }
}
