package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class LimitClause extends BaseConcept {
  public static final String concept = "DeCypher.structure.LimitClause";
  public static final String NUMBER = "number";

  public LimitClause(SNode node) {
    super(node);
  }

  public int getNumber() {
    return this.getIntegerProperty(LimitClause.NUMBER);
  }

  public void setNumber(int value) {
    this.setIntegerProperty(LimitClause.NUMBER, value);
  }

  public static LimitClause newInstance(SModel sm, boolean init) {
    return (LimitClause) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.LimitClause", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static LimitClause newInstance(SModel sm) {
    return LimitClause.newInstance(sm, false);
  }
}
