package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class LogicalWhereExpression extends WhereExpression {
  public static final String concept = "DeCypher.structure.LogicalWhereExpression";
  public static final String LEFT = "left";
  public static final String RIGHT = "right";

  public LogicalWhereExpression(SNode node) {
    super(node);
  }

  public WhereExpression getLeft() {
    return (WhereExpression) this.getChild(WhereExpression.class, LogicalWhereExpression.LEFT);
  }

  public void setLeft(WhereExpression node) {
    super.setChild(LogicalWhereExpression.LEFT, node);
  }

  public WhereExpression getRight() {
    return (WhereExpression) this.getChild(WhereExpression.class, LogicalWhereExpression.RIGHT);
  }

  public void setRight(WhereExpression node) {
    super.setChild(LogicalWhereExpression.RIGHT, node);
  }

  public static LogicalWhereExpression newInstance(SModel sm, boolean init) {
    return (LogicalWhereExpression) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.LogicalWhereExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static LogicalWhereExpression newInstance(SModel sm) {
    return LogicalWhereExpression.newInstance(sm, false);
  }
}
