package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class MinReturnTerm extends FunctionalReturnTerm {
  public static final String concept = "DeCypher.structure.MinReturnTerm";

  public MinReturnTerm(SNode node) {
    super(node);
  }

  public static MinReturnTerm newInstance(SModel sm, boolean init) {
    return (MinReturnTerm) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.MinReturnTerm", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static MinReturnTerm newInstance(SModel sm) {
    return MinReturnTerm.newInstance(sm, false);
  }
}
