package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class NodeReturnTerm extends ReturnTerm {
  public static final String concept = "DeCypher.structure.NodeReturnTerm";
  public static final String GRAPH_NODE = "graphNode";

  public NodeReturnTerm(SNode node) {
    super(node);
  }

  public GraphNodeReference getGraphNode() {
    return (GraphNodeReference) this.getChild(GraphNodeReference.class, NodeReturnTerm.GRAPH_NODE);
  }

  public void setGraphNode(GraphNodeReference node) {
    super.setChild(NodeReturnTerm.GRAPH_NODE, node);
  }

  public static NodeReturnTerm newInstance(SModel sm, boolean init) {
    return (NodeReturnTerm) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.NodeReturnTerm", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static NodeReturnTerm newInstance(SModel sm) {
    return NodeReturnTerm.newInstance(sm, false);
  }
}
