package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class NodeExpressionWhereTerm extends NodeReferringWhereTerm {
  public static final String concept = "DeCypher.structure.NodeExpressionWhereTerm";

  public NodeExpressionWhereTerm(SNode node) {
    super(node);
  }

  public static NodeExpressionWhereTerm newInstance(SModel sm, boolean init) {
    return (NodeExpressionWhereTerm) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.NodeExpressionWhereTerm", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static NodeExpressionWhereTerm newInstance(SModel sm) {
    return NodeExpressionWhereTerm.newInstance(sm, false);
  }
}
