package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class NodeStartTerm extends StartTerm {
  public static final String concept = "DeCypher.structure.NodeStartTerm";
  public static final String GRAPH_NODE = "graphNode";

  public NodeStartTerm(SNode node) {
    super(node);
  }

  public GraphNode getGraphNode() {
    return (GraphNode) this.getChild(GraphNode.class, NodeStartTerm.GRAPH_NODE);
  }

  public void setGraphNode(GraphNode node) {
    super.setChild(NodeStartTerm.GRAPH_NODE, node);
  }

  public static NodeStartTerm newInstance(SModel sm, boolean init) {
    return (NodeStartTerm) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.NodeStartTerm", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static NodeStartTerm newInstance(SModel sm) {
    return NodeStartTerm.newInstance(sm, false);
  }
}
