package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class NodesReturnTerm extends ReturnTerm {
  public static final String concept = "DeCypher.structure.NodesReturnTerm";

  public NodesReturnTerm(SNode node) {
    super(node);
  }

  public static NodesReturnTerm newInstance(SModel sm, boolean init) {
    return (NodesReturnTerm) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.NodesReturnTerm", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static NodesReturnTerm newInstance(SModel sm) {
    return NodesReturnTerm.newInstance(sm, false);
  }
}
