package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class NotWhereExpression extends WhereExpression {
  public static final String concept = "DeCypher.structure.NotWhereExpression";
  public static final String ORIGINAL = "original";

  public NotWhereExpression(SNode node) {
    super(node);
  }

  public WhereExpression getOriginal() {
    return (WhereExpression) this.getChild(WhereExpression.class, NotWhereExpression.ORIGINAL);
  }

  public void setOriginal(WhereExpression node) {
    super.setChild(NotWhereExpression.ORIGINAL, node);
  }

  public static NotWhereExpression newInstance(SModel sm, boolean init) {
    return (NotWhereExpression) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.NotWhereExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static NotWhereExpression newInstance(SModel sm) {
    return NotWhereExpression.newInstance(sm, false);
  }
}
