package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class OrWhereExpression extends LogicalWhereExpression {
  public static final String concept = "DeCypher.structure.OrWhereExpression";

  public OrWhereExpression(SNode node) {
    super(node);
  }

  public static OrWhereExpression newInstance(SModel sm, boolean init) {
    return (OrWhereExpression) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.OrWhereExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static OrWhereExpression newInstance(SModel sm) {
    return OrWhereExpression.newInstance(sm, false);
  }
}
