package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class PropertyReturnTerm extends ReturnTerm {
  public static final String concept = "DeCypher.structure.PropertyReturnTerm";
  public static final String PROPERTY_REFERENCE = "propertyReference";

  public PropertyReturnTerm(SNode node) {
    super(node);
  }

  public PropertyReference getPropertyReference() {
    return (PropertyReference) this.getChild(PropertyReference.class, PropertyReturnTerm.PROPERTY_REFERENCE);
  }

  public void setPropertyReference(PropertyReference node) {
    super.setChild(PropertyReturnTerm.PROPERTY_REFERENCE, node);
  }

  public static PropertyReturnTerm newInstance(SModel sm, boolean init) {
    return (PropertyReturnTerm) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.PropertyReturnTerm", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static PropertyReturnTerm newInstance(SModel sm) {
    return PropertyReturnTerm.newInstance(sm, false);
  }
}
