package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class PropertyExpressionWhereTerm extends PropertyReferringWhereTerm {
  public static final String concept = "DeCypher.structure.PropertyExpressionWhereTerm";

  public PropertyExpressionWhereTerm(SNode node) {
    super(node);
  }

  public static PropertyExpressionWhereTerm newInstance(SModel sm, boolean init) {
    return (PropertyExpressionWhereTerm) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.PropertyExpressionWhereTerm", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static PropertyExpressionWhereTerm newInstance(SModel sm) {
    return PropertyExpressionWhereTerm.newInstance(sm, false);
  }
}
