package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.lang.core.structure.Attribute;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Queries extends BaseConcept implements INamedConcept {
  public static final String concept = "DeCypher.structure.Queries";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String QUERIES = "queries";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public Queries(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(Queries.NAME);
  }

  public void setName(String value) {
    this.setProperty(Queries.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(Queries.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(Queries.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(Queries.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(Queries.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(Queries.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(Queries.VIRTUAL_PACKAGE, value);
  }

  public int getQueriesesCount() {
    return this.getChildCount(Queries.QUERIES);
  }

  public Iterator<Query> querieses() {
    return this.children(Query.class, Queries.QUERIES);
  }

  public List<Query> getQuerieses() {
    return this.getChildren(Query.class, Queries.QUERIES);
  }

  public void addQueries(Query node) {
    this.addChild(Queries.QUERIES, node);
  }

  public void insertQueries(Query prev, Query node) {
    this.insertChild(prev, Queries.QUERIES, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(Queries.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, Queries.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, Queries.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(Queries.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, Queries.SMODEL_ATTRIBUTE, node);
  }

  public static Queries newInstance(SModel sm, boolean init) {
    return (Queries) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.Queries", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Queries newInstance(SModel sm) {
    return Queries.newInstance(sm, false);
  }
}
