package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Query extends BaseConcept implements INamedConcept {
  public static final String concept = "DeCypher.structure.Query";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String WHERE_CLAUSE = "whereClause";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public Query(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(Query.NAME);
  }

  public void setName(String value) {
    this.setProperty(Query.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(Query.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(Query.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(Query.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(Query.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(Query.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(Query.VIRTUAL_PACKAGE, value);
  }

  public WhereClause getWhereClause() {
    return (WhereClause) this.getChild(WhereClause.class, Query.WHERE_CLAUSE);
  }

  public void setWhereClause(WhereClause node) {
    super.setChild(Query.WHERE_CLAUSE, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(Query.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, Query.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, Query.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(Query.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, Query.SMODEL_ATTRIBUTE, node);
  }

  public static Query newInstance(SModel sm, boolean init) {
    return (Query) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.Query", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Query newInstance(SModel sm) {
    return Query.newInstance(sm, false);
  }
}
