package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class RelationshipReturnTerm extends ReturnTerm {
  public static final String concept = "DeCypher.structure.RelationshipReturnTerm";
  public static final String REFERENCE = "reference";

  public RelationshipReturnTerm(SNode node) {
    super(node);
  }

  public RelationshipReference getReference() {
    return (RelationshipReference) this.getChild(RelationshipReference.class, RelationshipReturnTerm.REFERENCE);
  }

  public void setReference(RelationshipReference node) {
    super.setChild(RelationshipReturnTerm.REFERENCE, node);
  }

  public static RelationshipReturnTerm newInstance(SModel sm, boolean init) {
    return (RelationshipReturnTerm) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.RelationshipReturnTerm", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static RelationshipReturnTerm newInstance(SModel sm) {
    return RelationshipReturnTerm.newInstance(sm, false);
  }
}
