package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class RelationshipsReturnTerm extends ReturnTerm {
  public static final String concept = "DeCypher.structure.RelationshipsReturnTerm";

  public RelationshipsReturnTerm(SNode node) {
    super(node);
  }

  public static RelationshipsReturnTerm newInstance(SModel sm, boolean init) {
    return (RelationshipsReturnTerm) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.RelationshipsReturnTerm", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static RelationshipsReturnTerm newInstance(SModel sm) {
    return RelationshipsReturnTerm.newInstance(sm, false);
  }
}
