package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.baseLanguage.structure.IValidIdentifier;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Relationship extends BaseConcept implements IValidIdentifier {
  public static final String concept = "DeCypher.structure.Relationship";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public Relationship(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(Relationship.NAME);
  }

  public void setName(String value) {
    this.setProperty(Relationship.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(Relationship.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(Relationship.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(Relationship.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(Relationship.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(Relationship.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(Relationship.VIRTUAL_PACKAGE, value);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(Relationship.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, Relationship.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, Relationship.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(Relationship.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, Relationship.SMODEL_ATTRIBUTE, node);
  }

  public static Relationship newInstance(SModel sm, boolean init) {
    return (Relationship) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.Relationship", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Relationship newInstance(SModel sm) {
    return Relationship.newInstance(sm, false);
  }
}
