package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ReturnTerm extends BaseConcept {
  public static final String concept = "DeCypher.structure.ReturnTerm";

  public ReturnTerm(SNode node) {
    super(node);
  }

  public static ReturnTerm newInstance(SModel sm, boolean init) {
    return (ReturnTerm) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.ReturnTerm", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ReturnTerm newInstance(SModel sm) {
    return ReturnTerm.newInstance(sm, false);
  }
}
