package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class StartTerm extends BaseConcept {
  public static final String concept = "DeCypher.structure.StartTerm";
  public static final String GRAPH_NODE = "graphNode";

  public StartTerm(SNode node) {
    super(node);
  }

  public GraphNode getGraphNode() {
    return (GraphNode) this.getChild(GraphNode.class, StartTerm.GRAPH_NODE);
  }

  public void setGraphNode(GraphNode node) {
    super.setChild(StartTerm.GRAPH_NODE, node);
  }

  public static StartTerm newInstance(SModel sm, boolean init) {
    return (StartTerm) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.StartTerm", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static StartTerm newInstance(SModel sm) {
    return StartTerm.newInstance(sm, false);
  }
}
