package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class StarReturnTerm extends ReturnTerm {
  public static final String concept = "DeCypher.structure.StarReturnTerm";

  public StarReturnTerm(SNode node) {
    super(node);
  }

  public static StarReturnTerm newInstance(SModel sm, boolean init) {
    return (StarReturnTerm) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.StarReturnTerm", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static StarReturnTerm newInstance(SModel sm) {
    return StarReturnTerm.newInstance(sm, false);
  }
}
