package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class SumReturnTerm extends FunctionalReturnTerm {
  public static final String concept = "DeCypher.structure.SumReturnTerm";

  public SumReturnTerm(SNode node) {
    super(node);
  }

  public static SumReturnTerm newInstance(SModel sm, boolean init) {
    return (SumReturnTerm) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.SumReturnTerm", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static SumReturnTerm newInstance(SModel sm) {
    return SumReturnTerm.newInstance(sm, false);
  }
}
