package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TypeReturnTerm extends ReturnTerm {
  public static final String concept = "DeCypher.structure.TypeReturnTerm";
  public static final String REFERENCE = "reference";

  public TypeReturnTerm(SNode node) {
    super(node);
  }

  public RelationshipReference getReference() {
    return (RelationshipReference) this.getChild(RelationshipReference.class, TypeReturnTerm.REFERENCE);
  }

  public void setReference(RelationshipReference node) {
    super.setChild(TypeReturnTerm.REFERENCE, node);
  }

  public static TypeReturnTerm newInstance(SModel sm, boolean init) {
    return (TypeReturnTerm) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.TypeReturnTerm", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TypeReturnTerm newInstance(SModel sm) {
    return TypeReturnTerm.newInstance(sm, false);
  }
}
