package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TypeReturnTerm extends ReturnTerm {
  public static final String concept = "DeCypher.structure.TypeReturnTerm";

  public TypeReturnTerm(SNode node) {
    super(node);
  }

  public static TypeReturnTerm newInstance(SModel sm, boolean init) {
    return (TypeReturnTerm) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.TypeReturnTerm", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TypeReturnTerm newInstance(SModel sm) {
    return TypeReturnTerm.newInstance(sm, false);
  }
}
