package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class WhereExpression extends BaseConcept {
  public static final String concept = "DeCypher.structure.WhereExpression";

  public WhereExpression(SNode node) {
    super(node);
  }

  public static WhereExpression newInstance(SModel sm, boolean init) {
    return (WhereExpression) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.WhereExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static WhereExpression newInstance(SModel sm) {
    return WhereExpression.newInstance(sm, false);
  }
}
