package DeCypher.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class WhereClause extends BaseConcept {
  public static final String concept = "DeCypher.structure.WhereClause";
  public static final String BODY = "body";

  public WhereClause(SNode node) {
    super(node);
  }

  public WhereExpression getBody() {
    return (WhereExpression) this.getChild(WhereExpression.class, WhereClause.BODY);
  }

  public void setBody(WhereExpression node) {
    super.setChild(WhereClause.BODY, node);
  }

  public static WhereClause newInstance(SModel sm, boolean init) {
    return (WhereClause) SModelUtil_new.instantiateConceptDeclaration("DeCypher.structure.WhereClause", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static WhereClause newInstance(SModel sm) {
    return WhereClause.newInstance(sm, false);
  }
}
