package DeCypher.behavior;

/*Generated by MPS */


public class AndWhereExpression_BehaviorDescriptor extends LogicalWhereExpression_BehaviorDescriptor {
  public AndWhereExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.AndWhereExpression";
  }
}
