package DeCypher.behavior;

/*Generated by MPS */


public class AvgReturnRetm_BehaviorDescriptor extends FunctionalReturnTerm_BehaviorDescriptor {
  public AvgReturnRetm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.AvgReturnRetm";
  }
}
