package DeCypher.behavior;

/*Generated by MPS */


public class CollectReturnType_BehaviorDescriptor extends FunctionalReturnTerm_BehaviorDescriptor {
  public CollectReturnType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.CollectReturnType";
  }
}
