package DeCypher.behavior;

/*Generated by MPS */


public class CountReturnTerm_BehaviorDescriptor extends FunctionalReturnTerm_BehaviorDescriptor {
  public CountReturnTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.CountReturnTerm";
  }
}
