package DeCypher.behavior;

/*Generated by MPS */


public class DistinctReturnTerm_BehaviorDescriptor extends ReturnTerm_BehaviorDescriptor {
  public DistinctReturnTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.DistinctReturnTerm";
  }
}
