package DeCypher.behavior;

/*Generated by MPS */


public class FalseWhereExpression_BehaviorDescriptor extends NodeExpressionWhereTerm_BehaviorDescriptor {
  public FalseWhereExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.FalseWhereExpression";
  }
}
