package DeCypher.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class GraphNodeReference_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public GraphNodeReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.GraphNodeReference";
  }
}
