package DeCypher.behavior;

/*Generated by MPS */


public class IdInitialization_BehaviorDescriptor extends Initialization_BehaviorDescriptor {
  public IdInitialization_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.IdInitialization";
  }
}
