package DeCypher.behavior;

/*Generated by MPS */


public class IDReturnTerm_BehaviorDescriptor extends ReturnTerm_BehaviorDescriptor {
  public IDReturnTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.IDReturnTerm";
  }
}
