package DeCypher.behavior;

/*Generated by MPS */


public class IndexQuery_BehaviorDescriptor extends IndexQoL_BehaviorDescriptor {
  public IndexQuery_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.IndexQuery";
  }
}
