package DeCypher.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;

public class IndexLookup_BehaviorDescriptor extends IndexQoL_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor {
  public IndexLookup_BehaviorDescriptor() {
  }

  public String virtual_getFqName_1213877404258(SNode thisNode) {
    return INamedConcept_Behavior.virtual_getFqName_1213877404258(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.IndexLookup";
  }
}
