package DeCypher.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class IndexQoL_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public IndexQoL_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.IndexQoL";
  }
}
