package DeCypher.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class Initialization_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Initialization_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.Initialization";
  }
}
