package DeCypher.behavior;

/*Generated by MPS */


public class LengthReturnTerm_BehaviorDescriptor extends FunctionalReturnTerm_BehaviorDescriptor {
  public LengthReturnTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.LengthReturnTerm";
  }
}
