package DeCypher.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class LimitClause_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public LimitClause_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.LimitClause";
  }
}
