package DeCypher.behavior;

/*Generated by MPS */


public abstract class LogicalWhereExpression_BehaviorDescriptor extends NodeExpressionWhereTerm_BehaviorDescriptor {
  public LogicalWhereExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.LogicalWhereExpression";
  }
}
