package DeCypher.behavior;

/*Generated by MPS */


public class MaxReturnTerm_BehaviorDescriptor extends FunctionalReturnTerm_BehaviorDescriptor {
  public MaxReturnTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.MaxReturnTerm";
  }
}
