package DeCypher.behavior;

/*Generated by MPS */


public class MinReturnTerm_BehaviorDescriptor extends FunctionalReturnTerm_BehaviorDescriptor {
  public MinReturnTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.MinReturnTerm";
  }
}
