package DeCypher.behavior;

/*Generated by MPS */


public abstract class NodeExpressionWhereTerm_BehaviorDescriptor extends NodeReferringWhereTerm_BehaviorDescriptor {
  public NodeExpressionWhereTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.NodeExpressionWhereTerm";
  }
}
