package DeCypher.behavior;

/*Generated by MPS */


public class NodeStartTerm_BehaviorDescriptor extends StartTerm_BehaviorDescriptor {
  public NodeStartTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.NodeStartTerm";
  }
}
