package DeCypher.behavior;

/*Generated by MPS */


public class NodeReturnTerm_BehaviorDescriptor extends ReturnTerm_BehaviorDescriptor {
  public NodeReturnTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.NodeReturnTerm";
  }
}
