package DeCypher.behavior;

/*Generated by MPS */


public class NodesReturnTerm_BehaviorDescriptor extends ReturnTerm_BehaviorDescriptor {
  public NodesReturnTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.NodesReturnTerm";
  }
}
