package DeCypher.behavior;

/*Generated by MPS */


public class NodeReferringWhereTerm_BehaviorDescriptor extends WhereTerm_BehaviorDescriptor {
  public NodeReferringWhereTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.NodeReferringWhereTerm";
  }
}
