package DeCypher.behavior;

/*Generated by MPS */


public class NonNullReturnTerm_BehaviorDescriptor extends ReturnTerm_BehaviorDescriptor {
  public NonNullReturnTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.NonNullReturnTerm";
  }
}
