package DeCypher.behavior;

/*Generated by MPS */


public class NotWhereExpression_BehaviorDescriptor extends NodeExpressionWhereTerm_BehaviorDescriptor {
  public NotWhereExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.NotWhereExpression";
  }
}
