package DeCypher.behavior;

/*Generated by MPS */


public class OrWhereExpression_BehaviorDescriptor extends LogicalWhereExpression_BehaviorDescriptor {
  public OrWhereExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.OrWhereExpression";
  }
}
