package DeCypher.behavior;

/*Generated by MPS */


public class PropertyReturnTerm_BehaviorDescriptor extends ReturnTerm_BehaviorDescriptor {
  public PropertyReturnTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.PropertyReturnTerm";
  }
}
