package DeCypher.behavior;

/*Generated by MPS */


public class PropertyReferringWhereTerm_BehaviorDescriptor extends WhereTerm_BehaviorDescriptor {
  public PropertyReferringWhereTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.PropertyReferringWhereTerm";
  }
}
