package DeCypher.behavior;

/*Generated by MPS */


public class PropertyExpressionWhereTerm_BehaviorDescriptor extends PropertyReferringWhereTerm_BehaviorDescriptor {
  public PropertyExpressionWhereTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.PropertyExpressionWhereTerm";
  }
}
