package DeCypher.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class RelationshipReference_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public RelationshipReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.RelationshipReference";
  }
}
