package DeCypher.behavior;

/*Generated by MPS */


public class RelationshipStartTerm_BehaviorDescriptor extends StartTerm_BehaviorDescriptor {
  public RelationshipStartTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.RelationshipStartTerm";
  }
}
