package DeCypher.behavior;

/*Generated by MPS */


public class RelationshipsReturnTerm_BehaviorDescriptor extends ReturnTerm_BehaviorDescriptor {
  public RelationshipsReturnTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.RelationshipsReturnTerm";
  }
}
