package DeCypher.behavior;

/*Generated by MPS */


public class RelationshipReturnTerm_BehaviorDescriptor extends ReturnTerm_BehaviorDescriptor {
  public RelationshipReturnTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.RelationshipReturnTerm";
  }
}
