package DeCypher.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ReturnClause_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ReturnClause_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.ReturnClause";
  }
}
