package DeCypher.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class ReturnTerm_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ReturnTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.ReturnTerm";
  }
}
