package DeCypher.behavior;

/*Generated by MPS */


public class SimplePropertyWhereTerm_BehaviorDescriptor extends PropertyReferringWhereTerm_BehaviorDescriptor {
  public SimplePropertyWhereTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.SimplePropertyWhereTerm";
  }
}
