package DeCypher.behavior;

/*Generated by MPS */


public class SimpleNodeWhereTerm_BehaviorDescriptor extends NodeReferringWhereTerm_BehaviorDescriptor {
  public SimpleNodeWhereTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.SimpleNodeWhereTerm";
  }
}
