package DeCypher.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class StartTerm_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public StartTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.StartTerm";
  }
}
