package DeCypher.behavior;

/*Generated by MPS */


public class StarReturnTerm_BehaviorDescriptor extends ReturnTerm_BehaviorDescriptor {
  public StarReturnTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.StarReturnTerm";
  }
}
