package DeCypher.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class StartClause_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public StartClause_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.StartClause";
  }
}
