package DeCypher.behavior;

/*Generated by MPS */


public class SumReturnTerm_BehaviorDescriptor extends FunctionalReturnTerm_BehaviorDescriptor {
  public SumReturnTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.SumReturnTerm";
  }
}
