package DeCypher.behavior;

/*Generated by MPS */


public class TrueWhereExpression_BehaviorDescriptor extends WhereExpression_BehaviorDescriptor {
  public TrueWhereExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.TrueWhereExpression";
  }
}
