package DeCypher.behavior;

/*Generated by MPS */


public class TypeReturnTerm_BehaviorDescriptor extends ReturnTerm_BehaviorDescriptor {
  public TypeReturnTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.TypeReturnTerm";
  }
}
