package DeCypher.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class WhereExpression_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public WhereExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.WhereExpression";
  }
}
