package DeCypher.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class WhereClause_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public WhereClause_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.WhereClause";
  }
}
