package DeCypher.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class WhereTerm_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public WhereTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "DeCypher.structure.WhereTerm";
  }
}
