package DeCypher.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.SNodePointer;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.smodel.SNode;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.smodel.constraints.CanBeAParentContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class DistinctReturnTerm_Constraints extends BaseConstraintsDescriptor {
  private static SNodePointer canBeParentBreakingPoint = new SNodePointer("r:2a176b2b-102e-4f37-9118-66136ec0d803(DeCypher.constraints)", "7750257802048807535");

  public DistinctReturnTerm_Constraints() {
    super("DeCypher.structure.DistinctReturnTerm");
  }

  @Override
  public boolean hasOwnCanBeParentMethod() {
    return true;
  }

  @Override
  public boolean canBeParent(IOperationContext operationContext, SNode node, SNode node1, SNode node2, @Nullable CheckingNodeContext checkingNodeContext) {
    boolean result = static_canBeAParent(operationContext, new CanBeAParentContext(node, node1, node2));

    if (!(result) && checkingNodeContext != null) {
      checkingNodeContext.setBreakingNode(canBeParentBreakingPoint);
    }

    return result;
  }

  public static boolean static_canBeAParent(final IOperationContext operationContext, final CanBeAParentContext _context) {
    return _context.getChildConcept() == SNodeOperations.getNode("r:a03a72bf-9410-48bd-859b-9b1d8c00e8c5(DeCypher.structure)", "4975721382227412594") || _context.getChildConcept() == SNodeOperations.getNode("r:a03a72bf-9410-48bd-859b-9b1d8c00e8c5(DeCypher.structure)", "6594089058936980514") || _context.getChildConcept() == SNodeOperations.getNode("r:a03a72bf-9410-48bd-859b-9b1d8c00e8c5(DeCypher.structure)", "6594089058936980519") || _context.getChildConcept() == SNodeOperations.getNode("r:a03a72bf-9410-48bd-859b-9b1d8c00e8c5(DeCypher.structure)", "4975721382227574200") || _context.getChildConcept() == SNodeOperations.getNode("r:a03a72bf-9410-48bd-859b-9b1d8c00e8c5(DeCypher.structure)", "4975721382227553497");
  }
}
