package DeCypher.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Map;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.IScope;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseReferenceScopeProvider;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.ISelector;

public class PropertyReference_Constraints extends BaseConstraintsDescriptor {
  private static SNodePointer breakingNode_57atcm_a0a1a0a0a1a0b0a1a1 = new SNodePointer("r:2a176b2b-102e-4f37-9118-66136ec0d803(DeCypher.constraints)", "2541834658517141432");

  public PropertyReference_Constraints() {
    super("DeCypher.structure.PropertyReference");
  }

  @Override
  protected Map<String, PropertyConstraintsDescriptor> getNotDefaultProperties() {
    Map<String, PropertyConstraintsDescriptor> properties = new HashMap();
    properties.put("name", new BasePropertyConstraintsDescriptor("name", this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }

      @Override
      public boolean validateValue(SNode node, String propertyValue, IScope scope) {
        String propertyName = "name";
        return !((SPropertyOperations.getString(propertyValue)).contains(","));
      }
    });
    return properties;
  }

  @Override
  protected Map<String, ReferenceConstraintsDescriptor> getNotDefaultReferences() {
    Map<String, ReferenceConstraintsDescriptor> references = new HashMap();
    references.put("graphNode", new BaseReferenceConstraintsDescriptor("graphNode", this) {
      @Override
      public boolean hasOwnScopeProvider() {
        return true;
      }

      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseReferenceScopeProvider() {
          @Override
          public Object createSearchScopeOrListOfNodes(final IOperationContext operationContext, final ReferenceConstraintsContext _context) {
            Iterable<SNode> graphNodes = null;
            SNode query = SNodeOperations.getAncestor(_context.getEnclosingNode(), "DeCypher.structure.Query", true, false);
            if (query != null && SLinkOperations.getTarget(query, "startClause", true) != null) {
              graphNodes = ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(query, "startClause", true), "terms", true)).select(new ISelector<SNode, SNode>() {
                public SNode select(SNode it) {
                  return SLinkOperations.getTarget(it, "graphNode", true);
                }
              });
            }
            return graphNodes;
          }

          @Override
          public SNodePointer getSearchScopeValidatorNode() {
            return breakingNode_57atcm_a0a1a0a0a1a0b0a1a1;
          }
        };
      }
    });
    return references;
  }
}
