package DeCypher.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import jetbrains.mps.smodel.SNode;

public class FalseWhereExpression_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    this.append("false");
  }
}
