package DeCypher.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.textGen.TextGenManager;

public class IdInitialization_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    this.append("(");
    int length = ListSequence.fromList(SLinkOperations.getTargets(node, "ids", true)).count();
    for (int i = 0; i < length; i++) {
      TextGenManager.instance().appendNodeText(this.getContext(), this.getBuffer(), SLinkOperations.getTargets(node, "ids", true).get(i), this.getSNode());
      if (i < length - 1) {
        this.append(", ");
      }
    }
    this.append(")");

  }
}
