package DeCypher.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntention;
import jetbrains.mps.intentions.Intention;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class IncludeNullValues_Intention extends BaseIntention implements Intention {
  public IncludeNullValues_Intention() {
  }

  public String getConcept() {
    return "DeCypher.structure.NonNullReturnTerm";
  }

  public boolean isParameterized() {
    return false;
  }

  public boolean isErrorIntention() {
    return false;
  }

  public boolean isAvailableInChildNodes() {
    return true;
  }

  public String getDescription(final SNode node, final EditorContext editorContext) {
    return "Include Null Values";
  }

  public void execute(final SNode node, final EditorContext editorContext) {
    SNodeOperations.replaceWithAnother(node, SLinkOperations.getTarget(node, "propertyReturnTerm", true));
  }

  public String getLocationString() {
    return "DeCypher.intentions";
  }
}
